# Generated by Django 3.2 on 2021-04-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210416_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='is_set',
            new_name='is_active',
        ),
    ]
