# Generated by Django 3.2 on 2021-04-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_is_set_quiz_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender_identity',
            field=models.CharField(blank=True, choices=[('男性', '男性'), ('女性', '女性'), ('その他', 'その他'), ('未回答', '未回答')], default='未回答', max_length=30, null=True),
        ),
    ]
