export const FOLDER_LIST_REQUEST = "FOLDER_LIST_REQUEST";
export const FOLDER_LIST_SUCCESS = "FOLDER_LIST_SUCCESS";
export const FOLDER_LIST_FAIL = "FOLDER_LIST_FAIL";
export const FOLDER_LIST_RESET = "FOLDER_LIST_RESET";

export const FOLDER_SET_REQUEST = "FOLDER_SET_REQUEST";
export const FOLDER_SET_SUCCESS = "FOLDER_SET_SUCCESS";
export const FOLDER_SET_FAIL = "FOLDER_SET_FAIL";
export const FOLDER_RESET = "FOLDER_RESET";

export const FOLDER_DELETE_REQUEST = "FOLDER_DELETE_REQUEST";
export const FOLDER_DELETE_SUCCESS = "FOLDER_DELETE_SUCCESS";
export const FOLDER_DELETE_FAIL = "FOLDER_DELETE_FAIL";
export const FOLDER_DELETE_RESET = "FOLDER_DELETE_RESET";
