export const ALL_QUIZ_REQUEST = "ALL_QUIZ_REQUEST";
export const ALL_QUIZ_SUCCESS = "ALL_QUIZ_SUCCESS";
export const ALL_QUIZ_FAIL = "ALL_QUIZ_FAIL";
export const ALL_QUIZ_RESET = "ALL_QUIZ_RESET";

export const ACTIVE_QUIZ_SET_REQUEST = "ACTIVE_QUIZ_SET_REQUEST";
export const ACTIVE_QUIZ_SET_SUCCESS = "ACTIVE_QUIZ_SET_SUCCESS";
export const ACTIVE_QUIZ_SET_FAIL = "ACTIVE_QUIZ_SET_FAIL";
export const ACTIVE_QUIZ_RESET = "ACTIVE_QUIZ_RESET";

export const QUIZ_DELETE_REQUEST = "QUIZ_DELETE_REQUEST";
export const QUIZ_DELETE_SUCCESS = "QUIZ_DELETE_SUCCESS";
export const QUIZ_DELETE_FAIL = "QUIZ_DELETE_FAIL";
export const QUIZ_DELETE_RESET = "QUIZ_DELETE_RESET";
